name: Create release

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

jobs:
  expose-tag:
    name: Expose Tag
    runs-on: ubuntu-latest
    outputs:
      module-tag: ${{ steps.expose-tag.outputs.tag }}
      module-version: ${{ steps.expose-tag.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - name: Expose tag and version
        id: expose-tag
        run: |
          version="$(cat ${{ inputs.module }}/package.json | jq -r '.version')"
          tag="${{ inputs.module }}-$version"
          tag="${tag##*/}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT

  create-release:
    runs-on: ubuntu-latest
    # needs: [ expose-tag,  run-lint,  run-unit-tests ]
    needs: expose-tag
    permissions: 
      contents: write
    env: 
      path: ${{ inputs.module }}
      version: ${{ needs.expose-tag.outputs.module-version}}
      tag: ${{ needs.expose-tag.outputs.module-tag}}
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - name: Generate Release Draft
      id: generate-release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.tag }}  
        allowUpdates: true
        draft: true
        body: "This is a release draft for ${{ env.tag }}"

    - name: Build And Upload Artifacts To Release
      uses: ./.github/actions/build-module
      with: 
        module-path: ${{ env.path }}
        version: ${{ env.version }}
        tag: ${{ env.tag }}
        token: ${{ github.token }}

